### ISSUE TITLE
Табы и слайдеры страница Детально

### ISSUE THREAD

**Issue by KatyaMatya21** [KatyaMatya21/ARS#2]
Страница Детально ( часть рецепты ) 

Все для слайдеров сверстано.
Сделано переключение табов и подтабов.
Сделана инициализация и убивание слайдера в текущем табе по ресайзу.

Нужно сделать, чтобы не было слайдеров в десктопной версии, а в версии 1250 и мобильной - они подключались при переключении табов.

У меня не получается никак :(

**Comment by Rebnev** [comment]
Я вижу, что на странице что-то не так, но пока не могу понять, я думаю это вопрос стоит обсудить. Но, например, то что ты сделала событие resize debounce, к нему привязать функцию, если переключилась мобильная версия, сделать что-то, если обычная - что-то другое.
