### ISSUE TITLE
Высота документа на страницах Польза и Способы применения

### ISSUE THREAD

**Issue by KatyaMatya21** [KatyaMatya21/ARS#3]
На страницах Польза и Способы применения использовала плагин mansory для построения блоков в таком хитром виде

sly, который используется для прокрутки документа, высчитывает высоту, а потом только мансори выстраивает блоки как надо, а высота уже посчитана и остается какой была изначально - как быть?

**Comment by Rebnev** [comment]
Тут все просто, и является часть ответа на другой вопрос.
У плагинов в большинстве случаев есть методы и всяческие callback.
Если брать masonry, то у него они живут тут.
http://masonry.desandro.com/events.html
$grid.on( 'layoutComplete', onLayout );
Срабатывает, когда загружается сетка. Соответственно, у тебя есть sly, он по умолчанию загружается после загрузки страницы (это срабатывает раньше чем mansory), когда загружается mansory тебе нужно еще раз загрузить sly (перезагрузить).
Документация по sly.
https://github.com/darsain/sly/blob/master/docs/Methods.md
есть 3 основных метода init, destroy и reload (destroy+init). 

Как-то так.
var sly = new Sly(frame, options).init();
sly.realod();

**Comment by KatyaMatya21** [comment]
добавила убийство и создание слайдера при ресайзе страницы - мансори тоже починился
