### ISSUE TITLE
Карта

### ISSUE THREAD

**Issue by KatyaMatya21** [KatyaMatya21/ARS#5]
Доделать мобильную версию Где купить?

**Comment by Rebnev** [comment]
Отличный вопрос) И весьма конкретный)
Кликаешь на город, появляется карта с адресами в городе, (без перезагрузки страницы).
У элементов привязка к карте.

**Comment by KatyaMatya21** [comment]
Это я тоже для себя)

**Comment by Rebnev** [comment]
А, я думал это все для меня)

**Comment by KatyaMatya21** [comment]
первые три для тебя))
